const WEBP_FORMAT = 'webp'
const DESKTOP_LAYOUT = 'desktop'
const DESKTOP_PIXEL_DESTINY = 1
const PIXELS_DENSITY_COUNT = 4

export {
  WEBP_FORMAT,
  DESKTOP_LAYOUT,
  DESKTOP_PIXEL_DESTINY,
  PIXELS_DENSITY_COUNT
}
